version: "3.8"
#
volumes:
  vol-emqx-data:
    name: foo-emqx-data
  #  vol-emqx-etc:
  #    name: foo-emqx-etc
  vol-emqx-log:
    name: foo-emqx-log
#

services:
  node:
    container_name: node
    image: "node:14"
    working_dir: /home/node/app
    volumes:
      - ./app/:/home/node/exine_iot_app
    ports:
      - "3000:3000"
      - "3001:3001"
      - "80:3002"

    command: sh -c "npm install"
